
name: Run django tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: otusds
          POSTGRES_PASSWORD: otusds
          POSTGRES_DB: otusds
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: 1. Setup python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 2. Install pip
        run: |
          python -m pip install --upgrade pip

      - name: 3. Install pipenv
        run: |
          pip install pipenv

      - name: 4. Install dependencies
        run: |
          pipenv install --dev --system

      - name: 5. List dependencies
        run: |
          pip list

      - name: 6. Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: 7. Init data to database
        run: |
          python manage.py initdata

      - name: 8. Run test
        run: |
          python manage.py test app/tests/
